name: ourpass_auth_project
description: Design of an authentication system with flutter & firebase

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  firebase_core: 1.19.1
  cloud_firestore: 3.2.1
  shared_preferences: ^2.0.9
  provider: ^6.0.3
  gap: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true